application: signasol
version: 2-3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /SignasolCompany.hyperesources
  static_dir: SignasolCompany.hyperesources
- url: /images
  static_dir: images
- url: /css
  static_dir: css
  
- url: /.*
  script: signasol.app
  
libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest