application: signasol
version: 1-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /SignasolMainSite.resources
  static_dir: SignasolMainSite.resources
  
- url: /.*
  script: signasol.app
  
libraries:
- name: jinja2
  version: latest